### ISSUE TITLE
nextcloud

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#8] opened 2017-04-10 16:19 UTC
toolkit 1.5.3 and .4
can't create new users inside nextcloud - 
system asks for password verification but our default not working.

**Comment by haniavis** [comment] 2017-04-11 09:02
Can you explain more your setup? 
Is your mazizone connected to the Internet?
Which user you use to create new users?
Have you made any change in your Nextcloud installation?

**Comment by panosnethood** [comment] 2017-04-11 09:04
Check also, if you had been logged in at the administrator panel. The same happened to me yesterday, couldn't create an owncloud user, because I couldn't login as administrator, for which I will create another issue :-)

**Comment by deckspace** [comment] 2017-04-11 11:28
Can you explain more your setup?
raspberrypi 3 v1.5.3 in offline mode - logged into nextcloud interface no probs
Is your mazizone connected to the Internet?
not in this case though same issue if it is.
Which user you use to create new users?
there is only one user - admin
Have you made any change in your Nextcloud installation?
none

**Comment by panosnethood** [comment] 2017-04-11 12:22
Check also if you had been logged in at the portal as administrator. The same happened to me yesterday, couldn't create an owncloud user. But I couldn't also login as administrator at the portal, for which I created issue  #11 :-)

**Comment by haniavis** [comment] 2017-05-12 13:56
closing this as duplicate of #16

**Closed by haniavis** 2017-05-12 13:56 UTC
Labels: help wanted
